test(ruyipkg): remove an unreliable test case asserting debug logs
Debug logs are forced to a certain line width by Rich, and can get
wrapped by Rich to fit the imaginary terminal width, making the
assertion unreliable. Example failure on macOS CI:

```plain
>       assert "Repository() failed" in debug_output
E       assert 'Repository() failed' in "debug: [2026-07-13T12:03:20.655667] invalid git repo at              repo.py:416\n                                   ...p6nhwcfpr0th0000gn/T/pytest-of-runner/pytest-0/test_corrupt_dir_emits_debug_d0/packages-index and re-run ruyi update\n"
```

It is expected to have the needle string split into two in the middle of
the captured output. Because it's just a debug log, it's fine to just drop
the assertion and be done with it.

Signed-off-by: WANG Xuerui <wangxuerui@iscas.ac.cn>